apiVersion: v1
kind: Namespace
metadata:
  name: ecom-dev
  labels:
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecom-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecom-prod
  labels:
    environment: production
