apiVersion: v1
kind: Secret
metadata:
  name: ecom-secrets
  namespace: ecom-dev
type: Opaque
data:
  # Base64 encoded 'viva_lab_devops_secret_key_2026'
  JWT_SECRET: dml2YV9sYWJfZGV2b3BzX3NlY3JldF9rZXlfMjAyNg==
  # Base64 encoded 'admin'
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
